### ISSUE TITLE
App keeps crashing on galaxy note 9 android 8.1

### ISSUE THREAD

**Issue by Rings4** [KieronQuinn/TapTap#7]
Enabling the accessibility service shows popup that tap tap has stopped, and asks me to restart it, which then pops back up that it stopped. Tapping restart no longer pops it back up, and I can open the app normally, but no actions are run when I double tap the back of my phone. 

Every time I stop service and start it back up it repeats this issue.

**Comment by KieronQuinn** [comment]
This bug also seems to happen on Android 7, looking at a fix.

**Comment by KieronQuinn** [comment]
This should hopefully be fixed in alpha 0.2, please try it on that release

**Comment by Rings4** [comment]
> This should hopefully be fixed in alpha 0.2, please try it on that release

Thanks for trying to fix it, but unfortunately it still crashes whenever the service is enabled.

**Comment by KieronQuinn** [comment]
In that case, please provide a logcat.

**Comment by Rings4** [comment]
> In that case, please provide a logcat.

Sure thing. Can you explain what that it and how to provide it?

**Comment by sunsero** [comment]
Same on S7 / stock Android 8 no-root: TapTap crashes immediately when enabling it in the accessibility screen. After that TapTap tells the accessibility service would be enabled but it doesn't seem to detect the double tapping.

**Comment by lividhen** [comment]
> > In that case, please provide a logcat.
> 
> Sure thing. Can you explain what that it and how to provide it?

To get a logcat, enable developer options, then enable USB debugging, then, on a computer install the android platform tools (can be found here https://developer.android.com/studio/releases/platform-tools) then from the command line run "adb logcat >> logcat.txt" without quotes. While this is running, open the app on your phone, to make it crash, and what happened will be saved into the logcat.txt on you computer.

**Comment by Rings4** [comment]
> 
> 
> > > In that case, please provide a logcat.
> > 
> > 
> > Sure thing. Can you explain what that it and how to provide it?
> 
> A logcat is a log of all system and or app events, whether that be crashes, or just normal operation. To get a logcat, enable developer options, then enable USB debugging, then, on a computer install the android platform tools (can be found here https://developer.android.com/studio/releases/platform-tools) then from the command line run "adb logcat >> logcat.txt" without quotes. While this is running, open the app on your phone, to make it crash, and what happened will be saved into the logcat.txt on you computer.

Thanks! I went ahead and got myself a logcat of my device while trying to enable the accessibility service. Just wondering, since the logcat contains sensitive information such as my emails, how would I provide the parts you need? It's 49097 lines in total. Should I just ctrl-f the word "tap, tap" and send those lines?

**Comment by lividhen** [comment]
> > > > In that case, please provide a logcat.
> > > 
> > > 
> > > Sure thing. Can you explain what that it and how to provide it?
> > 
> > 
> > A logcat is a log of all system and or app events, whether that be crashes, or just normal operation. To get a logcat, enable developer options, then enable USB debugging, then, on a computer install the android platform tools (can be found here https://developer.android.com/studio/releases/platform-tools) then from the command line run "adb logcat >> logcat.txt" without quotes. While this is running, open the app on your phone, to make it crash, and what happened will be saved into the logcat.txt on you computer.
> 
> Thanks! I went ahead and got myself a logcat of my device while trying to enable the accessibility service. Just wondering, since the logcat contains sensitive information such as my emails, how would I provide the parts you need? It's 49097 lines in total. Should I just ctrl-f the word "tap, tap" and send those lines?

If I remember correctly, there is a way to get the log for certain processes, but I can't remember how, so I guess finding things realevent to taptap via ctrl f would work. Hopefully it is enough for Kieron to find the problem.

**Comment by dariusz-goc** [comment]
I'm having the same issue, Error thrown:

java.lang.UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods. Check that the correct native libraries are present, and, if using a custom native library, have been properly loaded via System.loadLibrary():
  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "fread_unlocked" referenced by "/data/app/com.kieronquinn.app.taptap-J_DeJtfX4az-BkzJlPLXSQ==/base.apk!/lib/arm64-v8a/libtensorflowlite_jni.so"...
	at org.tensorflow.lite.TensorFlowLite.init(Unknown Source:37)
	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(Unknown Source:20)
	at org.tensorflow.lite.Interpreter.<init>(Unknown Source:5)
	at org.tensorflow.lite.Interpreter.<init>(Unknown Source:1)
	at com.google.android.systemui.columbus.sensors.TfClassifier.<init>(Unknown Source:41)
	at com.google.android.systemui.columbus.sensors.TapRT.<init>(Unknown Source:95)
	at com.google.android.systemui.columbus.sensors.GestureSensorImpl.<init>(Unknown Source:79)
	at com.kieronquinn.app.taptap.TapAccessibilityService.onCreate(TapAccessibilityService.kt:64)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3340)
	at android.app.ActivityThread.-wrap4(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6499)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by KieronQuinn** [comment]
Was this fixed in 0.4 with the Tensorflow changes?

**Comment by Rings4** [comment]
> Was this fixed in 0.4 with the Tensorflow changes?

I didn't get to try 0.4 but I just downloaded 0.5 and it works! Thank you so much for fixing this!

**Comment by sunsero** [comment]
Wasn't fixed with 0.4 but works now with 0.5.Thanks!
